import "../(root)/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-bgGray text-white h-screen">
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
