import LeftSideBar from "@/components/LeftSideBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import RightSideBar from "@/components/RightSideBar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} w-screen h-screen bg-[#15202B] text-white overflow-y-auto overflow-x-hidden`}
      >
        <main className="w-5/6 max-w-7xl mx-auto flex justify-between gap-8 items-start">
          <LeftSideBar />
          <div className="flex-1">{children}</div>
          <RightSideBar />
        </main>
      </body>
    </html>
  );
}
